FROM python:3.13-slim

LABEL author="tlong-ds"
LABEL courses="mlops-fundamental"

COPY . .

WORKDIR /

RUN python -c "print('hello')"
RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 7860

CMD ["python", "main.py"]
