version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_answer
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
      